Feature/everyday award
AquaElephant/backend pull request #11
Opened 2024-07-31 22:20 UTC by alexfunt

2024-07-31 22:43 UTC, mikhailsnnt requested changes

2024-07-31 22:43 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/DailyReward.kt
> +    private fun getGoldReward(streakLength: Int): Int {
Это в гейм контфиг :)

2024-07-31 22:43 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/DailyReward.kt
> +        if (user.dailyClaimedAt >= now - 1.days) {
Ну, мелочи, но все же == здесь кажется лишнее

2024-07-31 22:43 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/DailyReward.kt
> +        val newStreakLength = if (user.dailyClaimedAt < now - 2.days) 1 else user.dailyStreakLength + 1
Еще нужно докупить зацикливание, что после 10-го, первый начинается

2024-07-31 22:43 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +            dailyRewardResult = dailyRewardResult
Да не, Саш, представь как это в Джоне будет выглядеть, 
{
gold:1,
water:3
....
dailyRewardResult:{
gold:1,
...
}
}
Подумай как ее фронту использовать. Тебе на фронте нужен только признак, можешь ли ты получить награду или нет

2024-07-31 22:58 UTC, alexfunt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/DailyReward.kt
> +        val newStreakLength = if (user.dailyClaimedAt < now - 2.days) 1 else user.dailyStreakLength + 1
я только об этом и подумал)

2024-07-31 23:00 UTC, alexfunt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +            dailyRewardResult = dailyRewardResult
хорошо, исправлю

2024-07-31 23:01 UTC, alexfunt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/DailyReward.kt
> +    private fun getGoldReward(streakLength: Int): Int {
хорошо, исправлю

2024-07-31 23:02 UTC, alexfunt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/DailyReward.kt
> +        if (user.dailyClaimedAt >= now - 1.days) {
типо исправить >= на >?

2024-08-01 09:01 UTC, mikhailsnnt requested changes

2024-08-01 09:01 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/DailyReward.kt
> +        val newStreakLength = if (user.dailyClaimedAt < now - 1.days - 1.hours) 1 else (user.dailyStreakLength % 10) + 1
А почему -1 hours , тоесть если прошло 24:55 минут мы хотим продолжить стрик?

2024-08-01 09:01 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/DailyReward.kt
> +class DailyReward(
Usecase это действие, название - глагол.

2024-08-01 09:01 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +        dailyRewardResult:
Тебе не нужно получать награду при получении данных для главного экрана (GET /state).
Вообще сразу ориентир что GET методы не должны менять состояние игры.  
На главном экране мы только отображаем признак "может ли пользователь получить награду", чтобы фронт если признак: true ,  - показал  кнопку получить награду, при нажатии на которую уже дернется эндпоинт получения награды

2024-08-01 09:01 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +        val dailyRewardResult = dailyReward.execute(userId)
Не изменять состояние при гет методах

2024-08-02 06:19 UTC, mikhailsnnt commented on app-ktor/src/main/kotlin/org/aquaelephant/app/ktor/routes/MainPageRoutes.kt
> +    val dailyReward by inject<DailyReward>()
ClaimDailyReward

2024-08-02 06:20 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +      parameters:
При мердже конфликтов упустил, я удалил это в своей ветке. Нужно убрать

2024-08-02 06:21 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +    ClaimDailyReward:
ClaimDailyReqardResult тогда уж для обнообразности

2024-08-02 06:29 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +            canClaimDailyReward = dailyReward.canClaimDailyReward(userId)
Приводит к лишнему запрозу в БД. Каждый запрос в БД это:
1) Время ожижания клиента
2) Деньги за запрос к БД ( у Dynamodb мы используем PayPerRequest)
3) Нагрузка на БД
Запросы нужно делать максимально - минимально. 
Все данные необходимые для определения canClaimDailyReward в сущности User, соответственно это лучше сделать методом класса User

2024-08-02 08:41 UTC, merged