Feature/set locale
AquaElephant/backend pull request #18
Opened 2024-08-04 16:54 UTC by alexfunt

2024-08-04 18:02 UTC, mikhailsnnt requested changes

2024-08-04 18:02 UTC, mikhailsnnt commented on app-ktor/src/main/kotlin/org/aquaelephant/app/ktor/routes/SettingsRoutes.kt
> +                "ru" -> org.aqua.elephant.core.usecase.Locale.RU
А зачем ты пересоздаешь объект?
Тебе приходит SetLocaleRequest и ты создаешь точно такуюже копию того же самого объекта, еще пропуская его через when

2024-08-04 18:02 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +      parameters:
Это параметры запросы. Ты вызывая .receive() получаешь объект из JSON Body запроса. Посмотри пример на /tap-water-from-well

2024-08-04 18:02 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +      properties:
Это лишнее

2024-08-04 18:02 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +      type: object
Респонйса у нас нет. Просто код 200 , ты же делаешь respond(OK)

2024-08-05 09:09 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/entity/User.kt
> +        return dailyClaimedAt > now() - 1.days
А это как ?

2024-08-05 09:09 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +      type: object
SetLocaleResult

2024-08-05 09:14 UTC, alexfunt commented on core/src/main/kotlin/org/aqua/elephant/core/entity/User.kt
> +        return dailyClaimedAt > now() - 1.days
это было так изначально:)
ты потом когда менял в другую сторону поставил знак и поэтому все тесты с ежедневным пошли неправильно

2024-08-05 10:22 UTC, mikhailsnnt requested changes

2024-08-05 10:22 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +              schema:
У тебя же нет тела ответа

2024-08-05 10:22 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +    SetLocaleResult:
У тебя же нет тела ответа у этого метода вообще

2024-08-05 10:54 UTC, mikhailsnnt approved these changes

2024-08-05 10:54 UTC, merged