Feature/breakage
AquaElephant/backend pull request #21
Opened 2024-08-15 19:11 UTC by alexfunt

i`l check tomorrow better by myself

2024-08-15 19:13 UTC, mikhailsnnt commented on app-ktor/src/main/kotlin/org/aquaelephant/app/ktor/routes/MainPageRoutes.kt
> -        val result = getTopPlayers.execute()
Сань, я все понимаю , но зачем метод удалять то?)

2024-08-15 19:13 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/config/GameConfig.kt
> +        3 to 150,
Это откуда тут?

2024-08-15 19:14 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/entity/User.kt
> +    var pumpState: PumpState,
Pump state это не состояние,  не переменная,  состояние колодца как и эффективность вычисляется по breakageAt

2024-08-15 19:17 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> -            val streakLength = user.newStreakLength()
Изменения которых ты не делал, видать в результате мержа

2024-08-15 19:18 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +            - SMALL_BREAK
Обновить контракт

2024-08-15 19:19 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +            pumpEfficiency = user.pumpEfficiency
Не все поля контракта реализованы

2024-08-15 19:19 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/PumpWaterFromWell.kt
> +    val pumpEfficiency: Double,
pumpEfficency не является результатом Вытачки воды из колодца

2024-08-15 19:21 UTC, mikhailsnnt commented on dynamodb/src/main/kotlin/org/aquaelephant/repo/dynamodb/impl/UserRepoImpl.kt
> +            pumpEfficiency = this["pumpEfficiency"]!!.asN().toDouble(),
pumpEfficency и pumpState не нужно сохранятьв БД, т.к они вычисляются по breakageAt. 
Красавчик что переименовал в breakageAt, но это нужно закончить доконца

2024-08-15 19:22 UTC, mikhailsnnt requested changes
Нужно поправить

2024-08-15 19:26 UTC, alexfunt commented on app-ktor/src/main/kotlin/org/aquaelephant/app/ktor/routes/MainPageRoutes.kt
> -        val result = getTopPlayers.execute()
🫢

2024-08-15 19:26 UTC, alexfunt commented on core/src/main/kotlin/org/aqua/elephant/core/config/GameConfig.kt
> +        3 to 150,
🤬🤬🤬🤬

2024-08-16 19:51 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +              description: Hours to fix breakages
Давай в минуты переделаем наверное

2024-08-16 19:53 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/service/impl/BreakageService.kt
> +    fun calculateRepairCost(pumplevel: Int): Int {
Разве тут уровень насоса должен быть?

2024-08-16 19:53 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/service/impl/BreakageService.kt
> +    fun getRepairTime(): Duration {
Это лучше в GameConfig. Как и RepairCost

2024-08-16 19:55 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +            goldToUpdateWell = gameConfig.wellLevelPrice(user.wellLevel),
Сравни goldToUpdateWell

2024-08-16 19:55 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +    val pumpState: String,
Почему enum как String передаешь?

2024-08-16 19:57 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +    val pumpEfficiency: Double,
Давай обойдемся без дробных чисел. Оставим pumpEfficency - [0 .. 100] . Чтобы в расчетах / 100 
Дробные числа это ненужная запара с точностью

2024-08-16 19:58 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/RepairBreakage.kt
> +    val repairCost: Int?,
Результат не соответствует контракту

2024-08-16 19:59 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +    val canClaimDailyReward: Boolean,
Почему добавилось новое поле?
Результат не соответствует контракту

2024-08-17 08:24 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +  /earn/check-actions:
Лишнее

2024-08-17 08:26 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/CoreModule.kt
> +    single { ClaimDailyReward(get(), get()) }
Откуда это здесь? В девелопе не объявляется этот use-case?

2024-08-17 08:29 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/entity/User.kt
> +    fun pumpEfficiency(): Int{
Давай тогда уж одинаково делать, или оба без calculate, или calculatePumpefficiency

2024-08-17 08:30 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +    val pumpRepair: PumpState,
Не соответствует контракту

2024-08-17 08:32 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/RepairBreakage.kt
> +        pumpRepair = if (code == RepairResultCode.REPAIR_STARTED) {
Для NOT_ENOUGH_GOLD поле  pumpRepair тоже актуально

2024-08-17 08:32 UTC, alexfunt commented on core/src/main/kotlin/org/aqua/elephant/core/CoreModule.kt
> +    single { ClaimDailyReward(get(), get()) }
ебучие конфликты, попозже исправлю

2024-08-17 08:32 UTC, alexfunt commented on core/src/main/kotlin/org/aqua/elephant/core/entity/User.kt
> +    fun pumpEfficiency(): Int{
есть такое

2024-08-17 08:32 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/RepairBreakage.kt
> +                time = (gameConfig.getRepairTime().inWholeHours).toInt(),
Договаривались в минутах

2024-08-17 08:33 UTC, alexfunt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +    val pumpRepair: PumpState,
типо мне не стоит так группировать, а все раздельно описать, да?

2024-08-17 08:35 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +    val pumpRepair: PumpState,
Сделай так как в контракте. Чтобы JSON на фронте получился такой, какой ожидают согласно spec.yaml

2024-08-18 16:53 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +  /repair:
Не соответствует реализации. В кторе ты сделал /repair-breakage,  давай так и сделаем. Чтобы место для починки школы оставить

2024-08-18 16:58 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +    val repairStartTime: Instant?,
Не соответствует контракту

2024-08-18 16:59 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/PumpWaterFromWell.kt
> +        val waterPerTap = (gameConfig.waterForTap(user) * (user.pumpEfficiency()))/100
Скобки раставленны странно. Путает децел

2024-08-18 17:02 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/RepairBreakage.kt
> +    private fun User.mapToResult(code: RepairResultCode) = RepairResult(
Не работает когда передаешь  NO_BREAKAGE. 
rapairStartTime не правильно. Что если у нас уже REPAIR_STARTED пол часа назад

2024-08-18 17:03 UTC, mikhailsnnt commented on dynamodb/src/test/kotlin/org/aquaelephant/repo/dynamodb/DbTestHelper.kt
> +        waterInWellUpdatedAt = waterInWellUpdatedAt.truncateToMilliseconds(),
Это наверное тоже из-за конфликтов, думаю это не из твоей ветки

2024-08-18 21:02 UTC, mikhailsnnt requested changes

2024-08-18 21:02 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +            pumpRepair = user.repairStartAt?.let {
Как это работает? PumpRepair только если repairStartAt?

2024-08-18 21:02 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/RepairBreakage.kt
> +                RepairResultCode.REPAIR_STARTED -> repairStartAt ?: now()
Что это ? В каком случае ?: now()

2024-08-19 06:00 UTC, mikhailsnnt requested changes

2024-08-19 06:00 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/GetMainState.kt
> +            pumpRepair = if (user.pumpState() == PumpState.BREAK && user.repairStartAt != null) {
А мы pumpRepair должны показывать только если колодец уже чинят?

2024-08-19 06:00 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/usecase/RepairBreakage.kt
> +data class RepairResult(
Давай одинаково называть. Или тогда Use-Case repair , или здесь RepairBreakage (так лучше , чтобы для школы оставить имя)

2024-08-19 06:00 UTC, mikhailsnnt commented on dynamodb/src/main/kotlin/org/aquaelephant/repo/dynamodb/impl/UserRepoImpl.kt
> +            ":repairStartAt" to AttributeValue.S(repairStartAt?.toEpochMilliseconds().toString()),
Почему время сохраняешь в виде числа, но как строку (тип S)

2024-08-19 06:00 UTC, mikhailsnnt commented on dynamodb/src/main/kotlin/org/aquaelephant/repo/dynamodb/impl/UserRepoImpl.kt
> +            ":repairPriceTotal" to AttributeValue.N(repairPriceTotal.toString())
И расположи пожалуйста атрибуты выше, version используется для оптимистичной конкурентности, этот атрибут будет хорошо смотреться самым последним

2024-08-20 06:43 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +#    url: https://api.dev.aquaelephant.org
Убрать

2024-08-20 06:43 UTC, alexfunt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +#    url: https://api.dev.aquaelephant.org
аааа

2024-08-20 06:45 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> -              type: integer
А вот эти поля не надо убирать. Это же в pumpUpgrade было

2024-08-20 06:45 UTC, mikhailsnnt commented on app-ktor/src/main/resources/openapi/spec.yaml
> +              description: Hours to fix breakages
Поправь description плиз

2024-08-20 06:46 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aqua/elephant/core/repo/UserRepo.kt
> +    suspend fun scanPeopleStatistics(topByPeopleLimit: Int, sumByPeopleDrankAtGreaterThen: Instant): StatisticScanResult
Не надо создавать новый UserRepo

2024-08-20 06:49 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/usecase/RepairBreakage.kt
> +        val repairStartTime: Instant?
repairStartAt давай везде сделаем

2024-08-20 08:28 UTC, merged