add squadId optional and filtered
AquaElephant/backend pull request #88
Opened 2024-10-24 11:18 UTC by alexfunt

2024-10-24 16:39 UTC, mikhailsnnt requested changes

2024-10-24 16:39 UTC, mikhailsnnt commented on core-integration-test/src/test/kotlin/org/aquaelephant/core/tests/integration/application/service/EventBroadcastListenerTest.kt
> +            eventBroadcastListener.getMessageSharedFlow(MessageChannel.SQUAD_STATISTICS).emit(jsonMessage)
Неее, надо реальный тест сделать, не эмитить ожидаемое значение.
Посмотри тест который я скидывал- у тебя юзеры должны реально сделать что-то, а ты апдейт считать

2024-10-24 16:40 UTC, mikhailsnnt requested changes

2024-10-24 16:40 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/application/service/EventBroadcastListener.kt
> +        val messageFlow = MutableSharedFlow<String>()
Не запускать новую. А просто вызвать функцию выше 

( чтобы если канал уже был - использовать его)

2024-10-30 12:18 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/application/service/EventBroadcastListener.kt
> +    fun getFilteredSquadStatisticsFlow(squadId: String? = null): SharedFlow<String> {
getSquadStatisticsMesssageFlowBySquadId

2024-10-30 12:41 UTC, mikhailsnnt commented on core-integration-test/src/test/kotlin/org/aquaelephant/core/tests/integration/application/service/EventBroadcastListenerTest.kt
> +        val squads = searchSquad.execute("")
Это от сюда лучше убрать, это не вопрос тестируемого класса

2024-10-30 12:41 UTC, mikhailsnnt commented on service/sse-statistics/src/main/kotlin/org/aquaelephant/sse/statistics/routes/SseRoute.kt
> +    route("sse") {
Поправь на statistics-sse плиз

2024-10-30 12:49 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/application/service/EventBroadcastListener.kt
> +    fun getMessageSharedFlow(channel: MessageChannel): MutableSharedFlow<String> {
Здесь как и выше нужно оставить SharedFlow< не mutable>

2024-10-30 12:52 UTC, mikhailsnnt commented on service/sse-statistics/src/main/kotlin/org/aquaelephant/sse/statistics/routes/SseRoute.kt
> +            if (squadId != null) {
Ты два раза вышлешь евенты вышлешь, если squadId != null

2024-10-30 12:54 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/application/service/EventBroadcastListener.kt
> +    fun getSquadStatisticsMessageFlowBySquadId(squadId: String? = null): SharedFlow<String> {
Не nullable

2024-10-30 13:13 UTC, mikhailsnnt commented on service/sse-statistics/src/main/kotlin/org/aquaelephant/sse/statistics/routes/SseRoute.kt
> +            val flowToCollect = if (squadId != null) {
squadStatisticsFlow тогда уж

2024-10-30 13:36 UTC, mikhailsnnt commented on service/sse-statistics/src/main/kotlin/org/aquaelephant/sse/statistics/routes/SseRoute.kt
> +            val squadId = call.request.queryParameters["SquadId"]
squadId

2024-10-30 13:36 UTC, alexfunt commented on service/sse-statistics/src/main/kotlin/org/aquaelephant/sse/statistics/routes/SseRoute.kt
> +            val squadId = call.request.queryParameters["SquadId"]
=))))))))))))))))))))))))))))))))))))

2024-10-30 13:37 UTC, merged