fix bug
AquaElephant/backend pull request #94
Opened 2024-11-06 11:42 UTC by alexfunt

2024-11-07 22:50 UTC, mikhailsnnt requested changes

2024-11-07 22:50 UTC, mikhailsnnt commented on worker/send-notifications/src/main/resources/Notifications_ru.properties
> +NotifyUpcomingPunishmentDto=Через 8 часов твои жители начнут страдать, ты потеряешь %s ❤️ кармы
Саш , а что это за уведомление такое ?)
У нас же все уведомления под ключем напримемр NotifyUpcomingPunishment24h и тп. 
Тоесть у нас на любые часы 8 будет написано)

2024-11-07 22:50 UTC, mikhailsnnt commented on worker/send-notifications/src/main/resources/Notifications_ru.properties
> +NotifyUpcomingPunishmentDto=Через 8 часов твои жители начнут страдать, ты потеряешь %s ❤️ кармы
Проблема в не правильном тесте. 

Но пожалуйста, перепроверь чтобы на каждое сообщение из этого списка был тест. 
Сейчас мы ловим баг!

 2024-11-07 14:34:57 ERROR [DefaultDispatcher-worker-4] o.a.w.n.l.NotificationListener - Exception processing notifications                                           │
│ worker-send-notifications-66f44bf8f9-56vl8 java.util.MissingFormatArgumentException: Format specifier '%s'                                                                                                      │
│ worker-send-notifications-66f44bf8f9-56vl8     at java.base/java.util.Formatter.format(Formatter.java:2688)                                                                                                     │
│ worker-send-notifications-66f44bf8f9-56vl8     at java.base/java.util.Formatter.format(Formatter.java:2625)                                                                                                     │
│ worker-send-notifications-66f44bf8f9-56vl8     at java.base/java.lang.String.format(String.java:4145)                                                                                                           │
│ worker-send-notifications-66f44bf8f9-56vl8     at org.aquaelephant.worker.notification.Localization.getLocalizedMessage(Localization.kt:19)                                                                     │
│ worker-send-notifications-66f44bf8f9-56vl8     at org.aquaelephant.worker.notification.impl.NotificationMessageFactory.localizedText(NotificationMessageFactory.kt:77)                                          │
│ worker-send-notifications-66f44bf8f9-56vl8     at org.aquaelephant.worker.notification.impl.NotificationMessageFactory.createMessage(NotificationMessageFactory.kt:17)                                          │
│ worker-send-notifications-66f44bf8f9-56vl8     at org.aquaelephant.worker.notification.listener.NotificationListener$startReceive$3$processedNotifications$1$1.invokeSuspend(NotificationListener.kt:31)        │
│ worker-send-notifications-66f44bf8f9-56vl8     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                        │
│ worker-send-notifications-66f44bf8f9-56vl8     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)

2024-11-08 12:16 UTC, mikhailsnnt requested changes

2024-11-08 12:16 UTC, mikhailsnnt commented on worker/send-notifications/src/main/kotlin/org/aquaelephant/worker/notification/impl/NotificationMessageFactory.kt
> +            is NotifyUpcomingPunishmentDto -> arrayOf(notification.applyIn, notification.willTakeKarma)
А разве ты в уведомлении используешь applyIn?

2024-11-08 12:16 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/domain/notification/Notifications.kt
> +    val applyIn: Duration
Что такое applyIn ? 
Зачем отдельное уведомление? 
В основном уведомлении есть же нужные данные

2024-11-08 15:05 UTC, mikhailsnnt requested changes

2024-11-08 15:05 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/application/service/UserFactory.kt
> +        bonusGiveWaterAvailableUntil = Instant.DISTANT_FUTURE,
Null. Не используем такое значение так как оно криво пишется в бд и вообще проблемы

2024-11-08 16:18 UTC, mikhailsnnt requested changes

2024-11-08 16:18 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/domain/entity/User.kt
> -            bonusGiveWaterAvailableUntil = null
Это здесь нужно)

2024-11-08 16:18 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/domain/entity/User.kt
> +                val calculateAvailableBonus = time + gameConfig.bonusGiveWaterTimeWindow
Название переменной

2024-11-08 16:18 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/domain/entity/User.kt
> +                val calculateAvailableBonus = time + gameConfig.bonusGiveWaterTimeWindow
И зачем она вообще

2024-11-08 16:18 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/domain/entity/User.kt
> +                notifications += NotifyAutoPumpGiveWaterHotDayDto(tgUserId, locale, calculateAvailableBonus)
Эмм, погодь 
В эту ветку же не только автопоилка попадет

2024-11-08 16:18 UTC, mikhailsnnt commented on worker/send-notifications/src/main/kotlin/org/aquaelephant/worker/notification/impl/NotificationMessageFactory.kt
> +            is NotifyAutoPumpGiveWaterHotDayDto -> arrayOf(notification.bonusGiveWaterAvailableUntil)
Форматируй в строку HH:mm

2024-11-08 18:13 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/domain/notification/Notifications.kt
> +data class NotifyGiveWaterHotDayDto(
Переименуй плиз в NotifyAutoPumpGiveWaterBonusAvailableDto

2024-11-08 18:16 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/domain/entity/User.kt
> +                notifications += NotifyCanGiveWaterDto(tgUserId, locale, people)
А это что за уведомление?

2024-11-08 18:16 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/domain/entity/User.kt
> +                notifications += NotifyGiveWaterHotDayDto(tgUserId, locale, time + gameConfig.bonusGiveWaterTimeWindow)
Это уведомление, мы шлем только для авттопоилки

2024-11-08 18:19 UTC, mikhailsnnt commented on core/src/main/kotlin/org/aquaelephant/core/domain/entity/User.kt
> +            notifications += NotifyAutoPumpGaveWaterDto(tgUserId, locale, people)
Тоесть суммарно мы вышлем 3 уведомления ?

Здесь два , и одно 5-ью строчками выше

2024-11-10 10:04 UTC, mikhailsnnt commented on worker/send-notifications/src/main/kotlin/org/aquaelephant/worker/notification/impl/NotificationMessageFactory.kt
> +            is NotifyPunishedDto -> arrayOf(notification.karmaTaken, notification.applyIn)
Разве мы используем applyIn в уведомлении об наказании

2024-11-10 10:05 UTC, alexfunt commented on worker/send-notifications/src/main/kotlin/org/aquaelephant/worker/notification/impl/NotificationMessageFactory.kt
> +            is NotifyPunishedDto -> arrayOf(notification.karmaTaken, notification.applyIn)
да

2024-11-10 10:11 UTC, mikhailsnnt commented on worker/send-notifications/src/main/kotlin/org/aquaelephant/worker/notification/impl/NotificationMessageFactory.kt
> +        val zone = TimeZone.currentSystemDefault()
Поставь TODO-шку плиз - получить таймзону пользователя . 
Сделаем чуть позже, пока нет времени - просто не передавай время (чуть позже функцию допилим).  В уведомлении  напиши прост "у тебя есть 3 часа"

2024-11-22 23:53 UTC, mikhailsnnt approved these changes

2024-11-22 23:53 UTC, merged